name: "Commit Message Validation"

on: 
  push:
  pull_request:
    branches:
      - devel

jobs:
  validate-commit-message:
    uses: dbeaver/dbeaver/.github/workflows/reused-commit-msgs-validator.yml@devel